/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kanishkagarg' at '9/9/18 10:57 PM' with Gradle 2.9
 *
 * @author kanishkagarg, @date 9/9/18 10:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
